### ISSUE TITLE
js error @ Google Chrome 43.0.2357.65 (64-bit), Mac OS 10.10.3

### ISSUE THREAD

**Issue by mistadikay** [iamstarkov/jsunderhood#1]
https://jsunderhood.ru/stats/

![screen shot 2015-05-25 at 21 44 29](https://cloud.githubusercontent.com/assets/742056/7798691/4bfe0fb8-0327-11e5-9ce5-4956dae0d940.png)

**Comment by iamstarkov** [comment]
=( need to include js inside project

**Comment by iamstarkov** [comment]
btw, why gauges is also blocked? is it some chrome plugin?

**Comment by mistadikay** [comment]
gaug.es was blocked by [this extension](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)

**Comment by iamstarkov** [comment]
Then it’s okay, i’m using ghostery and disconnect for the same goal.

**Comment by iamstarkov** [comment]
will fix this issue today

**Comment by mistadikay** [comment]
yeah, you don't have to fix ad-blockers. :smiley: Thanks!

**Comment by iamstarkov** [comment]
landed in 4347bc43d7011ba55b4d69e44a465f14cbf71c08
