### ISSUE TITLE
некорректный адрес при формировании твита по кнопке "Твитнуть"

### ISSUE THREAD

**Issue by greybax** [iamstarkov/jsunderhood#12]
Repro steps:
- Кликаем "Твитнуть" на главной странице [jsunderhood.ru](https://jsunderhood.ru/)
- Окно с твитом 
  ![undefined](https://cloud.githubusercontent.com/assets/3235047/7881043/b93e3372-0607-11e5-8070-c4a6309e50fc.png)

**Comment by iamstarkov** [comment]
😟 починю
