### ISSUE TITLE
Заэскейпленные символы <, > должны отображаться правильно в markdown

### ISSUE THREAD

**Issue by roman01la** [iamstarkov/jsunderhood#18]
Twitter API отдает твиты с заэскейпленными символами <, >. В markdown это ломает отображение кода в твите.

Такой твит: функция `id = x => x;`
Приходит в таком виде: функция `id = x =&gt; x;`
Соответственно в markdown: функция `id = x =&gt; x;`

**Comment by iamstarkov** [comment]
Это ведь на твоей странице происходит, верное?

**Comment by roman01la** [comment]
Что ты имеешь в виду?

**Comment by iamstarkov** [comment]
то есть на какой странице искать проблему и куда смотреть, чтобы она порешалась

**Comment by roman01la** [comment]
Судя по коду, дамп пишется напрямую из Twitter API, [вот здесь](https://github.com/iamstarkov/jsunderhood/blob/master/dump/roman01la.json#L11860) например видно, в каком виде приходит тело твита.

Я думаю, что можно было бы обрабатывать заескейпеленые символы [на этапе создания markdown файла с твитами](https://github.com/iamstarkov/jsunderhood/blob/master/posts.js#L36).  Определять строку с кодом, выделенную через ``, находить в ней заескейпленые символы и замещать соответствующими.

**Comment by roman01la** [comment]
Можно обрабатывать символы не только в строках с кодом, но и во всем тексте твита. Но тогда markdown не должен позволять вставлять HTML, что бы не получилась инъекция тега `<script>` с кодом, который будет выполнятся на странице.

Например, вот такой твит: `скрипт <script>alert(1)</script>`
придет в таком виде: `скрипт &lt;script&gt;alert(1)&lt;/script&gt;`
после обработки будет как изначальный: `скрипт <script>alert(1)</script>`

Если markdown модуль разрешает HTML, то твит так и войдет, и тогда на странице вылетит alert. Вместо этого нужно запретить HTML, что бы вставляся как текст.

Вот так выглядит твит в markdown c HTML: `<p>скрипт <script>alert(1)</script></p>`
во так без: `<p>скрипт &lt;script&gt;alert(1)&lt;/script&gt;</p>`

**Comment by iamstarkov** [comment]
починили https://jsunderhood.ru/roman01la/
![screen shot 2015-08-25 at 20 44 24](https://cloud.githubusercontent.com/assets/559321/9475945/1b3e6d4c-4b6a-11e5-8c75-840e8a85d75a.png)
