### ISSUE TITLE
Отставания статистики

### ISSUE THREAD

**Issue by subzey** [iamstarkov/jsunderhood#2]
Похоже, статистика отстаёт на три дня, и статистика не попадает точно по временным промежуткам в «эфиры» ведущих.

**Comment by iamstarkov** [comment]
статистика отстаёт на 3 дня
а значит предспоследний автор в таблице получает неправильное количество фолловеров
на начало недели текущего
ну и на конец своей тоже, соотв

**Comment by iamstarkov** [comment]
Починил в новой схеме получения данных https://jsunderhood.ru/stats/
