### ISSUE TITLE
Переименовать Ask_11 на alekseykulikov_

### ISSUE THREAD

**Issue by alekseykulikov** [iamstarkov/jsunderhood#21]
Привет.

Я недавно ради эксперимента переименовал свой твиттер аккаунт с [Ask_11](https://twitter.com/Ask_11) на [alekseykulikov_](https://twitter.com/alekseykulikov_). Я почему-то думал, что твиттер просто будет делать редирект, а он освободил имя и на него сразу же зарегестрировался какой-то бот... 

Я думаю, чтобы не путать людей, лучше переименовать. 
Извиняюсь и больше переименовать не буду :)

**Comment by iamstarkov** [comment]
постараюсь сделать до выходных

**Comment by iamstarkov** [comment]
готово https://jsunderhood.ru/alekseykulikov_/
Спасибо, @kinday !

**Comment by alekseykulikov** [comment]
Спасибо, ребята, так быстро!!
