### ISSUE TITLE
Список ссылок

### ISSUE THREAD

**Issue by slonoed** [iamstarkov/jsunderhood#23]
Было бы здорово для каждого пользователя кроме списка твитов иметь отдельно список ссылок в твитах (и может ретвитах).
Иногда хочется пробежать глазами в поисках новых штук, а читать глазами весь текст не всегда получается.
Сейчас можно из json доставать ссылки на внешние ресурсы, но может стоит прикрутить на jsunderhood.ru? Как вариант можно в последствии прикрутить логику по выбору лучших ссылок (например, исключая картинки, выдачу гугла, SO).

**Comment by iamstarkov** [comment]
идея отличная

**Comment by iamstarkov** [comment]
хочешь попробовать реализовать?

**Comment by slonoed** [comment]
@iamstarkov с большим удовольствием, если подскажешь где этот код должен жить (в каком файле), то будет вообще супер.

**Comment by iamstarkov** [comment]
Скрипт [posts.js](https://github.com/iamstarkov/jsunderhood/blob/master/posts.js), который запускается с помощью [npm run posts](https://github.com/iamstarkov/jsunderhood/blob/master/package.json#L10). Репозиторий нужно склонировать и установить зависимости `npm install`

**Comment by iamstarkov** [comment]
Если что-то не получится, спрашивай =)

**Comment by slonoed** [comment]
@iamstarkov хорошо, спасибо, постараюсь сделать.
