### ISSUE TITLE
Спец. символы markdown ломают текст

### ISSUE THREAD

**Issue by mistakster** [iamstarkov/jsunderhood#25]
Если в твите встречаются специальные символы разметки markdown (например, `_`), то они начинают преобразовываться в теги.

Хуже всего если такие символы без пары попадаются в никах или ссылках. Смотри страницу https://jsunderhood.ru/listochkin/ и сделай поиск «_sashashakun». Ещё пример на странице https://jsunderhood.ru/mistakster/ (ищи пользователя «_h4_»). Новом разделе «ссылки» такие непарные символы в URL приводят к забавным результатам.

**Comment by iamstarkov** [comment]
интересный кейс

**Comment by iamstarkov** [comment]
надо подумать

**Comment by mistakster** [comment]
Тут я вижу 2 проблемы:
1. символы в существующем тексте твита;
2. символы в генерируемом тексте (ссылки и т.п.).

Тебе, я так полагаю, нужно привести всё к одному формату хранения и манипулировать данными в одном формате. Тогда можно легко будет контролировать экранирование. Подозреваю, что это так же может решить https://github.com/iamstarkov/jsunderhood/issues/18

**Comment by iamstarkov** [comment]
Починили
![screen shot 2015-08-25 at 20 45 10](https://cloud.githubusercontent.com/assets/559321/9475964/3bf3bae2-4b6a-11e5-8f7f-5ebfab2f98b6.png)
![screen shot 2015-08-25 at 20 45 50](https://cloud.githubusercontent.com/assets/559321/9475973/4c270e28-4b6a-11e5-9b91-90d3a87ed675.png)
