### ISSUE TITLE
Ссылки на твиты

### ISSUE THREAD

**Issue by slonoed** [iamstarkov/jsunderhood#26]
Хочется иметь возможность посмотреть тредик к твиту, а для этого ссылку.
Сделать ссылки легко, но вот как их отобразить в текущем маркдауне не знаю.
Можно после каждого твита в конце, но будет выглядеть не очень, учитывая, что ссылки нельзя стилизовать (или можно?).

**Comment by iamstarkov** [comment]
> (или можно?).

можно, маркдаун подерживает html

Можно показывать ссылки только при ховере, чтобы избежать визуального шума:

> твит
> ⇓
> твит #

где # ссылка, c дополнительным `padding: 0.8em; margin: -0.8em;` чтобы не нарушать закон фитса

**Comment by slonoed** [comment]
@iamstarkov ховер не круто, так как на мобилках не видно

если говорить про стилизацию, то мне показалось неплохим вариантом сделать ссылку слева от твита, каким нибудь неприметным серым цветом

**Comment by slonoed** [comment]
ну или проверять мобильник или десктоп

**Comment by iamstarkov** [comment]
@kinday что ты думаешь?

**Comment by kinday** [comment]
Слева от твита можно писать время и оно будет ссылкой. Серым цветом или более мелким кеглем. Скрывать ничего не надо.

**Comment by iamstarkov** [comment]
Ширина колонки для ссылок — одна колонка? на мобильных располагать ссылки под твитами?

**Comment by A** [comment]
https://jsunderhood.ru/deepsweet/ — похоже ссылки не проверяются на уникальность. См. раздел facebook.github.io

**Comment by iamstarkov** [comment]
так и есть, надо `uniq` запускать по массиву перед редьюсом

**Comment by pgrekovich** [comment]
Еще надо слишком длинные ссылки обрезать. Пример c cssunderhood, но думаю тут тоже может повториться:
https://cssunderhood.ru/denysdovhan/
См. раздел "Другие"

**Comment by iamstarkov** [comment]
не думаю, что это частый кейс

**Comment by A** [comment]
Может просто `title` со страницы забирать и вместо ссылки вставлять если он есть, плюс добавить `text-overflow: ellipsis`?

**Comment by slonoed** [comment]
@skriming @shuvalov-anton там (в данных от твиттера) по дефолту есть урезанный вариант ссылок
мне он не понравился тем, что не понятно, что за кликом, но можно его использовать

**Comment by iamstarkov** [comment]
@shuvalov-anton можно каким-нибудь got грабить страницы по урлам, а затем парсить и получать title

**Comment by slonoed** [comment]
@iamstarkov сборка удлинится, некоторые урлы еще и парситься не будут

**Comment by iamstarkov** [comment]
повторяющиеся ссылки пофиксили

**Comment by iamstarkov** [comment]
ссылки на твиты можно оформить так /сс @kinday
![1439928201](https://cloud.githubusercontent.com/assets/559321/9455566/dbd30c96-4acc-11e5-9d0f-ba9b4ef14203.png)

**Comment by kinday** [comment]
@iamstarkov, сделано в #61

**Comment by iamstarkov** [comment]
готово https://jsunderhood.ru/shuvalov_anton/

**Comment by iamstarkov** [comment]
@kinday сделаешь анонс в твиттере?
