### ISSUE TITLE
Подписи структуры твитов

### ISSUE THREAD

**Issue by kinday** [iamstarkov/jsunderhood#3]
«RT» — неоднозначная подпись, можно подумать, что это ведущего ретвитнули.

Гораздо яснее будут восприниматься подписи вроде «Написал», «Ретвитнул», «Ответил».

**Comment by iamstarkov** [comment]
про /stats/

**Comment by iamstarkov** [comment]
я попробовал, как-то оно не так хорошо выглядит

**Comment by iamstarkov** [comment]
в основном потому что оно будет конфликтовать с подписми бара с цифрами

**Comment by iamstarkov** [comment]
возможно можно перенести пояснения в шапку таблицы, а в баре оставить только цифры

**Comment by iamstarkov** [comment]
и избавиться от второй строчки в этом столбце

**Comment by iamstarkov** [comment]
придумал что-то?

**Comment by kinday** [comment]
@iamstarkov, плотная неделя. В субботу будет много времени в дороге, вот там и придумаю.

**Comment by iamstarkov** [comment]
всё нормально. будет круто, я верю

**Comment by Rastopyr** [comment]
Подпишусь тут в связи закрытием #4
