### ISSUE TITLE
Легенда статистики

### ISSUE THREAD

**Issue by Rastopyr** [iamstarkov/jsunderhood#4]
https://jsunderhood.ru/stats/

Мне кажется вот тут неплохо было бы добавить "легенду" о том какие элементы что означают.

В чем разница между "ретвитами" и  "своими ретвитами"? Что за соотношение в двух правых столбцах?

Эти вещи указываются неявно, и предлагаю добавить либо какие нибудь тултипчики, или модальное окошко, с описанием.

**Comment by iamstarkov** [comment]
а как это выглядит?

**Comment by Rastopyr** [comment]
Вот пример текстовой легенды: ![Вот пример текстовой легенды](https://leto11e.storage.yandex.net/rdisk/30a2ab9f468757857c2ab31dfffa29eebf9eb9f7e13d15235eb9597db8da91f8/inf/Ix8apw_CKFKD0a0HyiFM_-6mxA1zHfTnFfqOuRHhm5GeGw6KYvGoB9XzaZzhaNreFHbXra5NUL3iHccX9mXphg==?uid=0&filename=2015-05-28%2011-09-04%20%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%3A%D0%9B%D0%B5%D0%B3%D0%B5%D0%BD%D0%B4%D0%B0%20%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B8%20%D1%82%D1%80%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%20%D0%9D%D0%91%D0%90%20%E2%80%94%20%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=876553fcd08c3e4d9acc94b407c85688&force_default=no)

Там указывается сокращение(иконка) и расшифровка.

**Comment by iamstarkov** [comment]
Похожая проблема тут #3

**Comment by iamstarkov** [comment]
я попробую сделать лучше, но не могу обещать, что станет лучше

**Comment by iamstarkov** [comment]
Поэтому если есть идеи, то можно прислать пулл-реквест

**Comment by Rastopyr** [comment]
А ты можешь скинуть описание вот этих вещей? Я попробую оформить информативно

> В чем разница между "ретвитами" и "своими ретвитами"? Что за соотношение в двух правых столбцах?

**Comment by iamstarkov** [comment]
загляни в шаблон https://github.com/iamstarkov/jsunderhood/blob/master/layouts/stats.jade

**Comment by iamstarkov** [comment]
написал своих твитов / ретвитнул / ответил
был ретвитнут на один твит / был ретвитнут
был добавлен в избранное на один твит / был добавлен в избранное

**Comment by iamstarkov** [comment]
написал своих твитов / ретвитнул / ответил
был ретвитнут на один твит / был ретвитнут
был добавлен в избранное на один твит / был добавлен в избранное

**Comment by iamstarkov** [comment]
ну как?

**Comment by Rastopyr** [comment]
сорян. еще не начинал. могу предложить появляющийся навбар с кнопкой "Легенда статистики" или как то так. что думаешь?

**Comment by Rastopyr** [comment]
забудь про навбар. завтра постараюсь с утра быстро оформить элегантно, и оформлю пул-реквест.

**Comment by iamstarkov** [comment]
👍

**Comment by kinday** [comment]
@Rastopyr, эта штука выглядит ещё хуже, чем нынешнее решение. Либо я не так понял.

**Comment by Rastopyr** [comment]
Вот так выглядит алерт для легенды. Появляетс когда верхняя часть экрана пересекает нижнюю часть блока `.jumbotron`. Жирный текст - ссылка. По клику на нее будет открываться модальное окошко.

![Алерт для легенды](https://leto46e.storage.yandex.net/rdisk/b86f229aa8f23ca21aeaf776270c0de44dfd6f4e62e004a7f33b82fba7ffda87/inf/VJvXpuPw8pCXH5njVh4kn3HIMp66uR_r2v7DQfqAQpGzcRvu-MIHUM2qAfh4S96K78qW4gMAA4lfvf85bKgqZg==?uid=0&filename=2015-05-29%2011-32-17%20%D0%A1%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B0%20%E2%80%A2%20jsunderhood.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=876553fcd08c3e4d9acc94b407c85688&force_default=no)

**Comment by Rastopyr** [comment]
Хочу предложить еще сюда добавить статическую ссылку.
Алерт нужен для того чтобы пользователь в области прогресбаров смог открыть легенду.
Статическая ссылка для того чтобы пользователь смог открыть легенду после того как закрыл alert.
![Статическая ссылка для модального окна легенды](https://leto15f.storage.yandex.net/rdisk/c5f012c68e57d1aec11b000267d6103b9aec7451e92b5b1133ea250737cd13c2/inf/U02vSwvbGsN9gB1JcTCanYZadKK-q4zTI1k6Ck2Jk4jGujcIMNaKSW3OJdW3c67KC12hUN4J0yhNIeYBlqN3mQ==?uid=0&filename=2015-05-29%2011-39-20%20%D0%A1%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B0%20%E2%80%A2%20jsunderhood.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=876553fcd08c3e4d9acc94b407c85688&force_default=no)

**Comment by iamstarkov** [comment]
Я кажется понял, но то как я понял, оно выглядит очень сложно. Можешь показать на реальном примере? (чтобы потыкать можно было, почувстовать)

**Comment by iamstarkov** [comment]
Я кажется понял, но то как я понял, оно выглядит очень сложно. Можешь показать на реальном примере? (чтобы потыкать можно было, почувстовать)

**Comment by kinday** [comment]
Выскажусь против. Легенда — решение хуже текущего.

**Comment by Rastopyr** [comment]
@iamstarkov ок. я вечерком сегодня доделаю полностью, отпишусь

**Comment by Rastopyr** [comment]
@kinday альтернатива?)

**Comment by kinday** [comment]
@Rastopyr, тут вопрос подачи, которая ведёт к неоднозначному восприятию. Легенда — костыль. Нужно изменить подачу. Думаю над этим.

**Comment by iamstarkov** [comment]
давайте я пока этот ишью закрою, так как он размылся и непонятно о чём он =(

**Comment by iamstarkov** [comment]
в любом случае, это не должно никого останавливать от открытия нового ишью или пр

**Comment by iamstarkov** [comment]
под закрытием я понимаю не то, что мне всё не нравится, нет. Всё хорошо с этим ишью.

просто ишью открыто с одним заголовком, а потом накинуто ещё несколько идей. Если кто-то разнесёт, это ишью в несколько разные: про саму легенду, про ссылку в меню, про попап — будет офигенно

**Comment by iamstarkov** [comment]
Написав пред сообщение, я понял, что это всё суть одно, только в разных частях страницы, что меня и запутало. Простите

**Comment by iamstarkov** [comment]
Переоткрыл, так как это всё таки одно исправление =)

**Comment by iamstarkov** [comment]
Вообще очень круто, что вам есть дело до этого сайта 😊

**Comment by Rastopyr** [comment]
@iamstarkov ок) я в целом согласен с @kinday. доделаю сегодня окошко, временно будет ок, пока не изменится подача информации.

**Comment by Rastopyr** [comment]
@kinday кстати что ты думаешь о небольшом динамическом графике на d3.js?
выпадающий список с именем твиттер-аккаунта, и рядом минималистичная легенда(описание графика)

**Comment by iamstarkov** [comment]
я не знаю, что думать (у меня плохо с воображением). Покажешь?

**Comment by kinday** [comment]
@iamstarkov, тоже не понял, что предлагается.

Вообще, половина проблем этого ишью решается фиксацией заголовка таблицы при прокрутке.

**Comment by Rastopyr** [comment]
вот пример динамичного пайчарта по твитам/ретвитам/реплаям
это только пример. тут по идее нужно добавить лейблы к кусочкам чарта, транзишены, для красивого перехода и так далее, но уже концепция понятна.

если есть смысл делать дальше то тогда я на выходных это все доделаю(допилю графики) и сделаю пул-реквест уже со всеми графиками.

список предлагаемых графиков с описанием.

**общие**
- динамика по новым подписчикам [пример](http://bl.ocks.org/mbostock/3883245)
- динамика по написанным твитам [пример](http://bl.ocks.org/mbostock/3883245)

**динамические(обновляются для каждого пользователя)**
- pie чарт как на примере ниже(с лейблами по каждому кусочку)

**предлагаю обсудить**
- какие графики подходят для соотношения ретвитов/избранных?

//cc @iamstarkov @kinday 
![example of dinamyc pie chart](http://g.recordit.co/uhi0BuU267.gif)

**Comment by iamstarkov** [comment]
Пай-чарты провал, если для них придётся использовать селект вместо таблицы

**Comment by iamstarkov** [comment]
я не понял как будут использоваться общие графики

**Comment by iamstarkov** [comment]
но это всё может быть оттого, что мы в разных контекстах с тобой. Просто куски графиков ни о чём не говорят, покажи как ты это видишь в конечном виде, тогда я смогу сказать хоть что-то

**Comment by Rastopyr** [comment]
@iamstarkov 

> Пай-чарты провал, если для них придётся использовать селект вместо таблицы

Я показал пример того, как график(и) могут рендерится через выбор автора. Ты хочешь сделать статистику всех авторов на одной странице?

> но это всё может быть оттого, что мы в разных контекстах с тобой. Просто куски графиков ни о чём не говорят, покажи как ты это видишь в конечном виде, тогда я смогу сказать хоть что-то

красивые подписи и оформление - очевидно да.

ок, попробую набросать за выходные как я это вижу.

**Comment by iamstarkov** [comment]
> Ты хочешь сделать статистику всех авторов на одной странице?

да

**Comment by iamstarkov** [comment]
> ок, попробую набросать за выходные как я это вижу.

спасибо 😊

**Comment by Rastopyr** [comment]
@iamstarkov хм. просто я думаю что через селект будет практичнее, чем куча информации в одной таблице. почему нет?

**Comment by iamstarkov** [comment]
ты задал хороший вопрос. я не знаю почему «нет», я сказал «да» таблице, так как практичность проверяется достижением целей. Я вижу две цели у этой страницы:
- для авторов — соревновательный момент
- для читатетелей — определить, кого почитать в архиве и на кого подписаться в тви

и так как соревноваться и выбирать удобно, когда видишь все варианты, то таблица подходит для этого хорошо

**Comment by iamstarkov** [comment]
а пай-чарты не сами по себе провал, конечно же. а потому что их нельзя вписать в таблицу

**Comment by Rastopyr** [comment]
В общем у меня пока нет идей как графиками решить те задачи которые ты ставишь перед этой страницей.
Селект для таких решений действительно провал.
Закрываю ишью.

**Comment by iamstarkov** [comment]
окай
