### ISSUE TITLE
Многострочные твиты не отображаются полностью

### ISSUE THREAD

**Issue by alexeyraspopov** [iamstarkov/jsunderhood#49]
Смотреть [здесь](https://jsunderhood.ru/pepelsbey/)

<img width="687" alt="2015-08-25 11 25 00" src="https://cloud.githubusercontent.com/assets/858295/9464322/b1b9c22e-4b2b-11e5-95f0-905b7bb576ed.png">

**Comment by silentroach** [comment]
Твиты отображаются целиком. Во всем виновато отсутствие визуального отделения твитов друг от друга.

<img width="687" alt="lalka" src="https://cloud.githubusercontent.com/assets/166803/9475582/33c88cca-4b70-11e5-8b14-39592ef58acd.png">

**Comment by silentroach** [comment]
после #52 станет немного более понятнее

**Comment by alexeyraspopov** [comment]
Закрываю в виду последнего обновления.

**Comment by iamstarkov** [comment]
@alexeyraspopov  А что-то поменялось?

**Comment by alexeyraspopov** [comment]
Появился более менее вменяемый отступ между твитами. Можешь сравнить скриншот из первого сообщения и то, как [сейчас выглядят](https://jsunderhood.ru/pepelsbey/) твиты.

**Comment by iamstarkov** [comment]
=( есть два момента которые меня печалят:
1. я не замечаю, что что-то поменялось
2. ничего поменяться не должно было.

**Comment by alexeyraspopov** [comment]
О как :)

В последнем обновлении учитываются переносы строк в твитах. Это то, что я сразу заметил. Именно те два твита, которые меня сначала смущали, сейчас выглядят намного лучше.

**Comment by iamstarkov** [comment]
есть неточность в реализации маркдаун-рендера silentroach/tweet.md#1
кажется из-за этого всё поменялось

**Comment by iamstarkov** [comment]
@alexeyraspopov @silentroach посмотрите теперь

**Comment by silentroach** [comment]
ну, переносы крутые стали, но разделителя все равно не хватает :)
ждем даты слева

**Comment by iamstarkov** [comment]
@silentroach дата слева уже в проде. стало лучше?

**Comment by silentroach** [comment]
да, визуально стало проще разделить.
но я бы еще попробовал какой-нибудь едва заметной чертой их разделить, чорт его знает

**Comment by kinday** [comment]
@silentroach, это будет шум и мусор. Смотреть нужно в сторону «швейцарского абзаца», когда высота отступа равна высоте строки.

**Comment by silentroach** [comment]
возможно

**Comment by iamstarkov** [comment]
швейцарский абзац для абзацев.
твиты по сути больше предложения, чем абзацы, мне кажется

**Comment by kinday** [comment]
Если это связанные твиты, то да, предложения, но не все твиты взаимосвязаны так, чтобы быть одним абзацем. Даже в рамках 10 минут.

# 

Вот демка:
![image](https://cloud.githubusercontent.com/assets/1751980/10480916/d3388a40-7275-11e5-8dc1-c4ed09fbffe6.png)

**Comment by iamstarkov** [comment]
последние 4 твита на скриншоте вполне себе связанные твиты
