### ISSUE TITLE
Длинные ссылки разносят ширину страницы на мобильниках

### ISSUE THREAD

**Issue by silentroach** [iamstarkov/jsunderhood#53]
На странице с твитами внизу есть блок ссылок. Большие ссылки делают страницу слишком широкой на мобильниках.

Было бы круто этим блокам добавить что-то вроде `overflow-x: hidden; text-overflow: ellipsis` (в сафари на ios все становится очень ок). Хз, правда, как это лучше сделать в markdown :{

**Comment by iamstarkov** [comment]
css one way

**Comment by iamstarkov** [comment]
можно попросить тебя вспомнить на какой странице и на каких твитах это происходит?
чтобы можно было уверенно сказать, что баг пофикшен и ишью можно закрывать

**Comment by silentroach** [comment]
@pepelsbey, к примеру

![ppsb](https://cloud.githubusercontent.com/assets/166803/10134229/ed8eba76-65ec-11e5-883b-fb2825aa18de.png)

**Comment by tachikombie** [comment]
Спасибо

**Comment by silentroach** [comment]
Уже лучше, но не совсем ок - некоторые ссылки разбиваются на несколько строк, в некоторых из которых эллипсисы одновременно

**Comment by iamstarkov** [comment]
покажи картинку пожалуйста

**Comment by pepelsbey** [comment]
@silentroach, вы же знаете, что как только кто-то упоминается, то он начинает получать уведомления о всех комментариях? Я-то отпишусь, но будьте осторожнее с этим.

**Comment by silentroach** [comment]
Сорян, больше так не буду

**Comment by silentroach** [comment]
![img_0017](https://cloud.githubusercontent.com/assets/166803/10162383/7a47a9ac-66b3-11e5-83dc-3a4d3bd5804b.jpg)

надо переносы запретить в ссылках просто, мне кажется
