### ISSUE TITLE
Механизм обновления андерхудов

### ISSUE THREAD

**Issue by pgrekovich** [iamstarkov/jsunderhood#57]
Круто было бы сделать какой нибудь механизм, что бы новые фичи появлялись не только на jsunderhood, но и cssunderhood и т.д.

**Comment by iamstarkov** [comment]
!["пони-пожималкин"](https://cloud.githubusercontent.com/assets/559321/9545090/922412ea-4d86-11e5-8669-58d42ac142f9.png)

**Comment by iamstarkov** [comment]
согласен, было бы круто. может быть

**Comment by iamstarkov** [comment]
you are welcome, to propose something

**Comment by pgrekovich** [comment]
просто я не знаю как это реализовать, возможно кто то другой знает...

**Comment by iamstarkov** [comment]
пока что механизм обновления ручной, и поэтому затратный

**Comment by silentroach** [comment]
запилить отдельную организацию
базовые штуки в отдельный репозиторий и npm-модуль, всюду его пользовать

**Comment by iamstarkov** [comment]
всё <del>чуть-чуть</del> сложнее

**Comment by silentroach** [comment]
Да, я понимаю :)

**Comment by iamstarkov** [comment]
будет генератор с миграционными скриптами

**Comment by iamstarkov** [comment]
here we go https://github.com/iamstarkov/generator-underhood/
