### ISSUE TITLE
Добавить ссылки на другие проекты *underhood

### ISSUE THREAD

**Issue by KSDaemon** [iamstarkov/jsunderhood#65]
Кажется неплохой идеей добавить где-то на главной странице каждого сайта *underhood ссылки на другие проекты разработческих коллективных твиттер-аккаунтов, таких как:
- @backendsecret
- @rubyunderhood
- @jsunderhood

**Comment by iamstarkov** [comment]
А можно дать ссылку на https://github.com/iamstarkov/awesome-collective-twitters

**Comment by ewnd9** [comment]
@iamstarkov а как человек случайно попавший на сайт получит эту ссылку?

**Comment by iamstarkov** [comment]
она будет в шапке и/или подвале

**Comment by ewnd9** [comment]
ещё в README.md проекта можно добавить

**Comment by iamstarkov** [comment]
можно
