### ISSUE TITLE
Новый формат файла твитов ломает сборку

### ISSUE THREAD

**Issue by kinday** [iamstarkov/jsunderhood#68]
Грязно и быстро починил в 588b975, но лучше привести старые дампы к новому формату.

**Comment by iamstarkov** [comment]
по идее вот так правильно было бы починить https://github.com/iamstarkov/jsunderhood/commit/fb4f0e0bd1edb4e35e2679795da5641c83c24709

**Comment by iamstarkov** [comment]
проблема с текущим форматом в том, что это некорректный json

**Comment by iamstarkov** [comment]
так как это должен быть JavaScript object в корне а не массив

**Comment by iamstarkov** [comment]
починилось
![image](https://cloud.githubusercontent.com/assets/559321/10870909/0ec48774-80d8-11e5-9fc3-ff4b548522b8.jpeg)
