### ISSUE TITLE
Лого

### ISSUE THREAD

**Issue by A** [iamstarkov/jsunderhood#73]
<img width="502" alt="screen shot 2015-11-09 at 00 59 30" src="https://cloud.githubusercontent.com/assets/1410106/11022969/50b964b0-867d-11e5-90ed-4804c5ae76e3.png">

@iamstarkov @kinday По-моему вполне годится как лого. Я бы как-нибудь цветом собаки мб подчеркнул, и всех ведущих в общем стиле оформил. Ну и меня давно тянет сделать наклейки и раздавать на конференциях. Что вы вообще думаете о лого?

**Comment by A** [comment]
У меня есть ещё один набросок, но пока не знаю что с ним делать.
![i15 pimgo_distr](https://cloud.githubusercontent.com/assets/1410106/11022997/e4e390de-867d-11e5-9db8-223f0cf836cc.jpeg)

**Comment by kinday** [comment]
> По-моему вполне годится как лого.

Не годится. Это обычный эскиз, который в процессе должен улететь в корзину.

> У меня есть ещё один набросок, но пока не знаю что с ним делать.

Выбросить. Это обычный эскиз, который должен улететь в корзину.

> Ну и меня давно тянет сделать наклейки и раздавать на конференциях.

Собственно, в этой фразе вся соль. Я очень люблю наклейки и не откажусь от андерхудовской, но она должна быть классной, а для этого нужен индивидуальный, клёвый и естественный логотип.

Да, от первого варианта (с собакой) веет естественностью, но на этом достоинства заканчиваются. Как я уже сказал, в качестве логотипа, это не более, чем набросок.

Последний мой монолог про дизайн закончился на мысли о том, что нужно эволюционно пилить текущий внешний вид и из него постепенно появится фирменный стиль и логотип (если уйти от бутстрапа). Эти события, конечно, можно форсировать, но лично я пока не могу.

---

**tl;dr** Давай не будем спешить.

**Comment by A** [comment]
@kinday Согласен, но наклейки уж очень охота…

**Comment by iamstarkov** [comment]
а что вы думаете об фавиконке?

**Comment by kinday** [comment]
Хотел добавить, но не придумал, что туда воткнуть в отсутствие логотипа. (:

**Comment by VovanR** [comment]
В продакшн!
![jsunderhood_superman_logo](https://cloud.githubusercontent.com/assets/430003/11118082/4832afa6-8950-11e5-9962-64f04d9cfc8d.png)

**Comment by iamstarkov** [comment]
котики, переоткройте когда что-нибудь будет, хорошо?
