### ISSUE TITLE
moment.js deprecation warning during build

### ISSUE THREAD

**Issue by mattjohnsonpint** [iamstarkov/jsunderhood#77]
Hello, I'm responding in reference to your comment here: https://github.com/moment/moment/issues/1407#issuecomment-155627465

I'm not familiar with your project or what it is intended to do, nor do I speak Russian, but I thought I would give you a hand to see where the deprecation warning stems from.

In your [gulpfile.babel.js](https://github.com/iamstarkov/jsunderhood/blob/a61813e87aaa75a532c6c9035812c7b145b093fb/gulpfile.babel.js#L96), you call `articleData(readme)`.  However, the article-data's default function is defined [here](https://github.com/iamstarkov/article-data/blob/9e1b514c0b628f325a10ea3a9a6c1976c0b963d1/index.js#L7), as `export default (input, dateFormat, dateLocale)`.

Since you don't pass `dateFormat` or `dateLocale`, then calling `getDate` and ultimately `moment` passes `undefined` for these, ultimately giving the error.

Pass some parameters for these fields and that warning goes away.  For example;

``` javascript
const article = articleData(readme, 'L', 'ru');
```

Of course, I'm not sure what format or locale you really are scanning for, so you may need to supply different parameters.

You can leave the locale blank, but the format is required.  If you want, you can pass an array of formats, such as:

``` javascript
const article = articleData(readme, ['YYYY.MM.DD', 'DD.MM.YYYY', 'YYYY-MM-DD[T]HH:mm:ss']);
```

or whatever you need.

Hope this helps.
-matt

**Comment by iamstarkov** [comment]
shame on me, you are right

**Comment by iamstarkov** [comment]
👍 great detective work

**Comment by iamstarkov** [comment]
landed in https://github.com/iamstarkov/jsunderhood/commit/9179f3b4b0d9a22f9595c329ae5be8721e639aa3

**Comment by mattjohnsonpint** [comment]
Empty string will still give the error.  Pass either a specific format like `'YYYY-MM-DD HH:mm:ss'`, or a locale specifier like `'L'`

**Comment by iamstarkov** [comment]
you are right, the reason why I tried with empty format is moment/moment#2527 and you are right it didnt work out with empty format, so for now we will live with `en` locale https://github.com/iamstarkov/jsunderhood/commit/a700b433ddd5fc8f5a48e2157899da372437be97

**Comment by iamstarkov** [comment]
thank you so much for investigation and help
