### ISSUE TITLE
Улучшение миграций

### ISSUE THREAD

**Issue by kinday** [iamstarkov/jsunderhood#81]
Подтянуть раннер из #79 и сделать в миграциях проверки на то, нужно ли их исполнять, чтобы не прогонять случайно дважды и не ломать всё к чертям.

**Comment by iamstarkov** [comment]
а скрипт сам себя может удалять в nodejs?

**Comment by kinday** [comment]
Теоретически да, но мы же обсудили вопрос с удалением.

**Comment by iamstarkov** [comment]
я забыл =(

**Comment by iamstarkov** [comment]
точнее не забыл, помню, что обсуждали но не могу вспомнить к чему пришли

**Comment by kinday** [comment]
Миграции лежат в репо, потому что обновление может потребовать более одной миграции. Каждая из них в процессе проверяет, нужна ли она, и пропускает изменения, если не нужна. Всё.

Главное, соблюдать очерёдность применения. Это можно делать префиксом в имени файла в виде даты `YYYYMMDD` или версии.

**Comment by iamstarkov** [comment]
так как пришли к генератору, то вопрос миграций отпал. @kinday ты всё равно крутой! 🎈
