### ISSUE TITLE
почему нет комментов в коде ?

### ISSUE THREAD

**Issue by jt3k** [iamstarkov/jsunderhood#82]

**Comment by iamstarkov** [comment]
Привет, оправдываться не вижу смысла, поэтому задам встречный вопрос: почему тебя это волнует?

**Comment by jt3k** [comment]
Решил почетать , а там мясушко без коментов. Поучаствовать в разработке не удастся видимо т.к. долго въезжать :)

**Comment by iamstarkov** [comment]
ну мясушко маленькое — каждое не больше 100 строчек

**Comment by iamstarkov** [comment]
спрашивай непонятные моменты тут, думаю поможем

**Comment by jt3k** [comment]
Ок, спс.

**Comment by iamstarkov** [comment]
у нас есть roadmap https://github.com/iamstarkov/jsunderhood/blob/master/roadmap.md
