### ISSUE TITLE
Смена ника: delaz → ihorzenich

### ISSUE THREAD

**Issue by ihorzenich** [iamstarkov/jsunderhood#88]
Я решил сменить ник во всех социалках и сервисах на ihorzenich, чтоб навести порядок и облегчить репосты между сервисами и поиск. Как сделать так, чтоб это переименование не поломало статистику jsunderhood?

**Comment by iamstarkov** [comment]
ты можешь переименовываться когда тебе будет угодно, после того, как переименуешься отпишись тут. переименуем и тут

**Comment by ihorzenich** [comment]
Переименовался.
