### ISSUE TITLE
IP сайта в чёрном списке РосКомНадзора

### ISSUE THREAD

**Issue by mistakster** [iamstarkov/jsunderhood#93]
Привет.

Несколько месяцев назад IP сайта был внесён в реестр и начал блокироваться провайдерами.

```
$ ping jsunderhood.ru

Pinging jsunderhood.ru [104.24.109.25] with 32 bytes of data:
Request timed out.
Request timed out.
```

```
$ tracert jsunderhood.ru

Tracing route to jsunderhood.ru [104.24.109.25]
over a maximum of 30 hops:

  1    19 ms    21 ms     9 ms  192.168.1.1
  2    22 ms    10 ms    12 ms  pool-31-207-192-1.is74.ru [31.207.192.1]
  3    16 ms    19 ms    16 ms  10.100.14.89
  4     *        *        *     Request timed out.
  5     *        *        *     Request timed out.
  6     *        *        *     Request timed out.
```

Выписка с сайта https://eais.rkn.gov.ru/

![image](https://cloud.githubusercontent.com/assets/531671/15236888/a09c7fe2-18e2-11e6-9c01-0565691592f9.png)

Попробуйте обратиться в CloudFlare, чтобы они перенесли сайт на другой IP. Их поддержка знает о блокировках и обещается содействовать в решении таких проблем.

Спасибо.

**Comment by iamstarkov** [comment]
Шта

**Comment by iamstarkov** [comment]
Спасибо за то, что сообщил

**Comment by DenisIzmaylov** [comment]
Что за основания?

**Comment by DenisIzmaylov** [comment]
По домену всё ОК

**Comment by mistakster** [comment]
А никто не писал про домен. @DenisIzmaylov, вы же знаете, что на одном IP адресе могут хоститься множество сайтов. Вот страница на каком-то из соседних сайтов и была внесена в реестр. А из-за того, что сайты отдаются по HTTPS, провайдеры не могут заблокировать одну конкретную страницу. В результате они блокируют весь IP-адрес.

**Comment by DenisIzmaylov** [comment]
Именно поэтому я и написал "по домену".

**Comment by iamstarkov** [comment]
написал в саппорт

**Comment by reklatsmasters** [comment]
Вот он тот сайт http://reestr.rublacklist.net/rec/64904/

**Comment by RReverser** [comment]
WAT

**Comment by denysdovhan** [comment]
![image](https://cloud.githubusercontent.com/assets/3459374/15383540/7ef2ba8c-1d9c-11e6-9401-bda556431a6c.png)

**Comment by iamstarkov** [comment]
@RReverser yep, Request #988632

**Comment by mistakster** [comment]
@iamstarkov, ping. 🙄

**Comment by iamstarkov** [comment]
@mistakster сап, ухожу от cloudlare

**Comment by RReverser** [comment]
@iamstarkov nooooo :)

**Comment by iamstarkov** [comment]
i had hope, but support couldnt help

**Comment by iamstarkov** [comment]
good news everyone https://geektimes.ru/post/289947/

**Comment by iamstarkov** [comment]
надо воспользоваться этой уникальной возможностью

**Comment by iamstarkov** [comment]
как раз отпраздную день рождения этого замечательного ишью

**Comment by mistakster** [comment]
Не совсем понятно как ей воспользоваться. Тут же заблокирован IP, а не домен.

**Comment by mistakster** [comment]
Кстати сказать, CF изменил адреса и теперь сайт открывается нормально. Я проверил эти адреса в https://eais.rkn.gov.ru/ — никаких претензий к ним нет.

Думаю, ишью можно закрывать. А?

**Comment by iamstarkov** [comment]
:(( думаю да
